#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include "hlv_battery_enhancement.hpp"
#include "hlv_bms_middleware_v2.hpp"
#include "torque_enhancement.hpp"

namespace py = pybind11;

PYBIND11_MODULE(hlv_enhancer_pybind, m) {
    m.doc() = "pybind11 Python bindings for HLV EV Battery Enhancement Software Core";

    // ========================================================================
    // Core HLV Structs & Classes
    // ========================================================================

    py::class_<hlv::HLVConfig>(m, "HLVConfig")
        .def(py::init<>())
        .def_readwrite("enable_feen_battery_integration", &hlv::HLVConfig::enable_feen_battery_integration)
        .def_readwrite("lambda", &hlv::HLVConfig::lambda)
        .def_readwrite("tau_min", &hlv::HLVConfig::tau_min)
        .def_readwrite("phi_decay_rate", &hlv::HLVConfig::phi_decay_rate)
        .def_readwrite("landauer_beta", &hlv::HLVConfig::landauer_beta)
        .def_readwrite("entropy_weight", &hlv::HLVConfig::entropy_weight)
        .def_readwrite("nominal_capacity_ah", &hlv::HLVConfig::nominal_capacity_ah)
        .def_readwrite("nominal_voltage", &hlv::HLVConfig::nominal_voltage)
        .def_readwrite("max_temperature", &hlv::HLVConfig::max_temperature)
        .def_readwrite("min_temperature", &hlv::HLVConfig::min_temperature)
        .def_readwrite("max_current", &hlv::HLVConfig::max_current)
        .def_readwrite("energy_conservation_tolerance", &hlv::HLVConfig::energy_conservation_tolerance)
        .def("validate", &hlv::HLVConfig::validate);

    py::class_<hlv::HealthPrediction>(m, "HealthPrediction")
        .def(py::init<>())
        .def_readwrite("remaining_capacity_percent", &hlv::HealthPrediction::remaining_capacity_percent)
        .def_readwrite("cycles_to_80_percent", &hlv::HealthPrediction::cycles_to_80_percent)
        .def_readwrite("estimated_eol_cycles", &hlv::HealthPrediction::estimated_eol_cycles)
        .def_readwrite("confidence", &hlv::HealthPrediction::confidence)
        .def_readwrite("warning_triggered", &hlv::HealthPrediction::warning_triggered)
        .def_readwrite("degradation_rate", &hlv::HealthPrediction::degradation_rate)
        .def_readwrite("time_to_80_percent_years", &hlv::HealthPrediction::time_to_80_percent_years);

    py::class_<hlv::OptimalChargingProfile>(m, "OptimalChargingProfile")
        .def(py::init<>())
        .def_readwrite("recommended_current_limit", &hlv::OptimalChargingProfile::recommended_current_limit)
        .def_readwrite("recommended_voltage_limit", &hlv::OptimalChargingProfile::recommended_voltage_limit)
        .def_readwrite("recommended_temperature", &hlv::OptimalChargingProfile::recommended_temperature)
        .def_readwrite("estimated_charge_time", &hlv::OptimalChargingProfile::estimated_charge_time)
        .def_readwrite("degradation_impact", &hlv::OptimalChargingProfile::degradation_impact)
        .def_readwrite("max_safe_current", &hlv::OptimalChargingProfile::max_safe_current)
        .def_readwrite("max_safe_voltage", &hlv::OptimalChargingProfile::max_safe_voltage);

    py::class_<hlv::HLVState>(m, "HLVState")
        .def(py::init<>())
        .def_readwrite("voltage", &hlv::HLVState::voltage)
        .def_readwrite("current", &hlv::HLVState::current)
        .def_readwrite("temperature", &hlv::HLVState::temperature)
        .def_readwrite("state_of_charge", &hlv::HLVState::state_of_charge)
        .def_readwrite("entropy", &hlv::HLVState::entropy)
        .def_readwrite("cycle_count", &hlv::HLVState::cycle_count)
        .def_readwrite("degradation", &hlv::HLVState::degradation)
        .def_readwrite("phi_magnitude", &hlv::HLVState::phi_magnitude)
        .def_readwrite("lambda", &hlv::HLVState::lambda)
        .def_readwrite("grad_phi", &hlv::HLVState::grad_phi)
        .def_readwrite("energy_psi", &hlv::HLVState::energy_psi)
        .def_readwrite("energy_phi", &hlv::HLVState::energy_phi)
        .def_readwrite("energy_metric", &hlv::HLVState::energy_metric)
        .def_readwrite("energy_total", &hlv::HLVState::energy_total);

    py::class_<hlv::EnhancedState>(m, "EnhancedState")
        .def(py::init<>())
        .def_readwrite("feen_trust_metric", &hlv::EnhancedState::feen_trust_metric)
        .def_readwrite("state", &hlv::EnhancedState::state)
        .def_readwrite("health", &hlv::EnhancedState::health)
        .def_readwrite("charging", &hlv::EnhancedState::charging)
        .def_readwrite("degradation_warning", &hlv::EnhancedState::degradation_warning)
        .def_readwrite("hlv_confidence", &hlv::EnhancedState::hlv_confidence)
        .def_readwrite("input_clamped", &hlv::EnhancedState::input_clamped)
        .def_readwrite("energy_conservation_error", &hlv::EnhancedState::energy_conservation_error)
        .def_readwrite("numerical_stability", &hlv::EnhancedState::numerical_stability);

    // ========================================================================
    // Middleware Structs & Classes
    // ========================================================================

    py::class_<hlv_plugin::DiagnosticReport>(m, "DiagnosticReport")
        .def(py::init<>())
        .def_readwrite("pack_soh_percent", &hlv_plugin::DiagnosticReport::pack_soh_percent)
        .def_readwrite("pack_soc_percent", &hlv_plugin::DiagnosticReport::pack_soc_percent)
        .def_readwrite("estimated_range_km", &hlv_plugin::DiagnosticReport::estimated_range_km)
        .def_readwrite("cycles_to_eol", &hlv_plugin::DiagnosticReport::cycles_to_eol)
        .def_readwrite("pack_health_percent", &hlv_plugin::DiagnosticReport::pack_health_percent)
        .def_readwrite("estimated_remaining_cycles", &hlv_plugin::DiagnosticReport::estimated_remaining_cycles)
        .def_readwrite("total_cells", &hlv_plugin::DiagnosticReport::total_cells)
        .def_readwrite("weak_cell_count", &hlv_plugin::DiagnosticReport::weak_cell_count)
        .def_readwrite("weak_cell_ids", &hlv_plugin::DiagnosticReport::weak_cell_ids)
        .def_readwrite("min_cell_voltage", &hlv_plugin::DiagnosticReport::min_cell_voltage)
        .def_readwrite("max_cell_voltage", &hlv_plugin::DiagnosticReport::max_cell_voltage)
        .def_readwrite("voltage_imbalance_mv", &hlv_plugin::DiagnosticReport::voltage_imbalance_mv)
        .def_readwrite("average_cell_temp_c", &hlv_plugin::DiagnosticReport::average_cell_temp_c)
        .def_readwrite("max_cell_temp_c", &hlv_plugin::DiagnosticReport::max_cell_temp_c)
        .def_readwrite("min_cell_temp_c", &hlv_plugin::DiagnosticReport::min_cell_temp_c)
        .def_readwrite("hlv_metric_trace", &hlv_plugin::DiagnosticReport::hlv_metric_trace)
        .def_readwrite("hlv_entropy", &hlv_plugin::DiagnosticReport::hlv_entropy)
        .def_readwrite("hlv_phi_magnitude", &hlv_plugin::DiagnosticReport::hlv_phi_magnitude)
        .def_readwrite("hlv_confidence", &hlv_plugin::DiagnosticReport::hlv_confidence)
        .def_readwrite("weak_cell_warning", &hlv_plugin::DiagnosticReport::weak_cell_warning)
        .def_readwrite("thermal_warning", &hlv_plugin::DiagnosticReport::thermal_warning)
        .def_readwrite("voltage_warning", &hlv_plugin::DiagnosticReport::voltage_warning)
        .def_readwrite("degradation_warning", &hlv_plugin::DiagnosticReport::degradation_warning)
        .def_readwrite("balancing_required", &hlv_plugin::DiagnosticReport::balancing_required)
        .def_readwrite("safety_fault", &hlv_plugin::DiagnosticReport::safety_fault)
        .def_readwrite("instantaneous_power_kw", &hlv_plugin::DiagnosticReport::instantaneous_power_kw)
        .def_readwrite("average_efficiency", &hlv_plugin::DiagnosticReport::average_efficiency)
        .def_readwrite("energy_throughput_kwh", &hlv_plugin::DiagnosticReport::energy_throughput_kwh)
        .def_readwrite("last_update_time_ms", &hlv_plugin::DiagnosticReport::last_update_time_ms)
        .def_readwrite("average_update_time_ms", &hlv_plugin::DiagnosticReport::average_update_time_ms)
        .def_readwrite("degradation_rate_per_cycle", &hlv_plugin::DiagnosticReport::degradation_rate_per_cycle)
        .def_readwrite("metric_trace", &hlv_plugin::DiagnosticReport::metric_trace)
        .def_readwrite("phi_magnitude", &hlv_plugin::DiagnosticReport::phi_magnitude)
        .def_readwrite("entropy_level", &hlv_plugin::DiagnosticReport::entropy_level)
        .def_readwrite("time_since_init_s", &hlv_plugin::DiagnosticReport::time_since_init_s)
        .def_readwrite("update_count", &hlv_plugin::DiagnosticReport::update_count);

    py::class_<hlv_plugin::SafetyLimits>(m, "SafetyLimits")
        .def(py::init<>())
        .def_readwrite("min_cell_voltage", &hlv_plugin::SafetyLimits::min_cell_voltage)
        .def_readwrite("max_cell_voltage", &hlv_plugin::SafetyLimits::max_cell_voltage)
        .def_readwrite("min_pack_voltage", &hlv_plugin::SafetyLimits::min_pack_voltage)
        .def_readwrite("max_pack_voltage", &hlv_plugin::SafetyLimits::max_pack_voltage)
        .def_readwrite("max_discharge_current", &hlv_plugin::SafetyLimits::max_discharge_current)
        .def_readwrite("max_charge_current", &hlv_plugin::SafetyLimits::max_charge_current)
        .def_readwrite("min_operating_temp", &hlv_plugin::SafetyLimits::min_operating_temp)
        .def_readwrite("max_operating_temp", &hlv_plugin::SafetyLimits::max_operating_temp)
        .def_readwrite("max_cell_temp", &hlv_plugin::SafetyLimits::max_cell_temp)
        .def_readwrite("min_soc", &hlv_plugin::SafetyLimits::min_soc)
        .def_readwrite("max_soc", &hlv_plugin::SafetyLimits::max_soc)
        .def_readwrite("max_voltage_imbalance_mv", &hlv_plugin::SafetyLimits::max_voltage_imbalance_mv)
        .def_readwrite("min_health_percent", &hlv_plugin::SafetyLimits::min_health_percent);

    py::class_<hlv_plugin::MiddlewareConfig> config(m, "MiddlewareConfig");

    py::enum_<hlv_plugin::MiddlewareConfig::Mode>(config, "Mode")
        .value("SIMPLE", hlv_plugin::MiddlewareConfig::Mode::SIMPLE)
        .value("SINGLE_BATTERY", hlv_plugin::MiddlewareConfig::Mode::SINGLE_BATTERY)
        .value("MULTI_CELL_PACK", hlv_plugin::MiddlewareConfig::Mode::MULTI_CELL_PACK)
        .value("ADVANCED_ML", hlv_plugin::MiddlewareConfig::Mode::ADVANCED_ML)
        .export_values();

    config.def(py::init<>())
        .def_readwrite("mode", &hlv_plugin::MiddlewareConfig::mode)
        .def_readwrite("chemistry", &hlv_plugin::MiddlewareConfig::chemistry)
        .def_readwrite("nominal_capacity_ah", &hlv_plugin::MiddlewareConfig::nominal_capacity_ah)
        .def_readwrite("nominal_voltage", &hlv_plugin::MiddlewareConfig::nominal_voltage)
        .def_readwrite("series_cells", &hlv_plugin::MiddlewareConfig::series_cells)
        .def_readwrite("hlv_config", &hlv_plugin::MiddlewareConfig::hlv_config)
        .def_readwrite("enable_kalman_filter", &hlv_plugin::MiddlewareConfig::enable_kalman_filter)
        .def_readwrite("enable_ml_hybrid", &hlv_plugin::MiddlewareConfig::enable_ml_hybrid)
        .def_readwrite("enable_cell_balancing", &hlv_plugin::MiddlewareConfig::enable_cell_balancing)
        .def_readwrite("safety_limits", &hlv_plugin::MiddlewareConfig::safety_limits)
        .def_readwrite("enable_safety_monitoring", &hlv_plugin::MiddlewareConfig::enable_safety_monitoring)
        .def_readwrite("enable_logging", &hlv_plugin::MiddlewareConfig::enable_logging)
        .def_readwrite("logging_interval_s", &hlv_plugin::MiddlewareConfig::logging_interval_s);

    py::enum_<hlv::advanced::ChemistryType>(m, "ChemistryType")
        .value("LFP", hlv::advanced::ChemistryType::LFP)
        .value("NMC", hlv::advanced::ChemistryType::NMC)
        .value("NCA", hlv::advanced::ChemistryType::NCA)
        .value("LTO", hlv::advanced::ChemistryType::LTO)
        .value("CUSTOM", hlv::advanced::ChemistryType::CUSTOM)
        .export_values();

    py::class_<hlv_plugin::HLVBMSMiddleware>(m, "HLVBMSMiddleware")
        .def(py::init<>())
        .def("init", &hlv_plugin::HLVBMSMiddleware::init, py::arg("capacity_ah"), py::arg("voltage_v"))
        .def("init_advanced", &hlv_plugin::HLVBMSMiddleware::init_advanced, py::arg("cfg"))
        .def("enhance_cycle", &hlv_plugin::HLVBMSMiddleware::enhance_cycle, py::arg("v"), py::arg("i"), py::arg("t"), py::arg("soc"), py::arg("dt"))
        .def("get_diagnostics", &hlv_plugin::HLVBMSMiddleware::get_diagnostics)
        .def("get_health_forecast", &hlv_plugin::HLVBMSMiddleware::get_health_forecast, py::arg("cycles_ahead") = 100.0)
        .def("get_status_summary", &hlv_plugin::HLVBMSMiddleware::get_status_summary)
        .def("snapshot", &hlv_plugin::HLVBMSMiddleware::snapshot);

    // ========================================================================
    // Torque Enhancement Module
    // ========================================================================

    py::enum_<hlv::drive::DriveMode>(m, "DriveMode")
        .value("ECO", hlv::drive::DriveMode::ECO)
        .value("NORMAL", hlv::drive::DriveMode::NORMAL)
        .value("SPORT", hlv::drive::DriveMode::SPORT)
        .value("CUSTOM", hlv::drive::DriveMode::CUSTOM)
        .export_values();

    py::enum_<hlv::drive::RegenMode>(m, "RegenMode")
        .value("LOW", hlv::drive::RegenMode::LOW)
        .value("MEDIUM", hlv::drive::RegenMode::MEDIUM)
        .value("HIGH", hlv::drive::RegenMode::HIGH)
        .value("ADAPTIVE", hlv::drive::RegenMode::ADAPTIVE)
        .export_values();

    py::class_<hlv::drive::MotorConfig>(m, "MotorConfig")
        .def(py::init<>())
        .def_readwrite("peak_torque_nm", &hlv::drive::MotorConfig::peak_torque_nm)
        .def_readwrite("continuous_torque_nm", &hlv::drive::MotorConfig::continuous_torque_nm)
        .def_readwrite("base_speed_rpm", &hlv::drive::MotorConfig::base_speed_rpm)
        .def_readwrite("max_speed_rpm", &hlv::drive::MotorConfig::max_speed_rpm)
        .def_readwrite("efficiency_peak_rpm", &hlv::drive::MotorConfig::efficiency_peak_rpm)
        .def_readwrite("peak_power_kw", &hlv::drive::MotorConfig::peak_power_kw)
        .def_readwrite("continuous_power_kw", &hlv::drive::MotorConfig::continuous_power_kw)
        .def_readwrite("max_motor_temp_c", &hlv::drive::MotorConfig::max_motor_temp_c)
        .def_readwrite("max_inverter_temp_c", &hlv::drive::MotorConfig::max_inverter_temp_c)
        .def_readwrite("thermal_derating_start_c", &hlv::drive::MotorConfig::thermal_derating_start_c)
        .def_readwrite("inverter_derating_start_c", &hlv::drive::MotorConfig::inverter_derating_start_c)
        .def_readwrite("torque_rise_rate_nm_per_s", &hlv::drive::MotorConfig::torque_rise_rate_nm_per_s)
        .def_readwrite("torque_fall_rate_nm_per_s", &hlv::drive::MotorConfig::torque_fall_rate_nm_per_s)
        .def_readwrite("peak_efficiency", &hlv::drive::MotorConfig::peak_efficiency)
        .def_readwrite("idle_efficiency", &hlv::drive::MotorConfig::idle_efficiency);

    py::class_<hlv::drive::DrivetrainConfig>(m, "DrivetrainConfig")
        .def(py::init<>())
        .def_readwrite("front_motor", &hlv::drive::DrivetrainConfig::front_motor)
        .def_readwrite("rear_motor", &hlv::drive::DrivetrainConfig::rear_motor)
        .def_readwrite("has_front_motor", &hlv::drive::DrivetrainConfig::has_front_motor)
        .def_readwrite("has_rear_motor", &hlv::drive::DrivetrainConfig::has_rear_motor)
        .def_readwrite("final_drive_ratio", &hlv::drive::DrivetrainConfig::final_drive_ratio)
        .def_readwrite("wheel_radius_m", &hlv::drive::DrivetrainConfig::wheel_radius_m)
        .def_readwrite("vehicle_mass_kg", &hlv::drive::DrivetrainConfig::vehicle_mass_kg)
        .def_readwrite("front_weight_dist", &hlv::drive::DrivetrainConfig::front_weight_dist)
        .def_readwrite("drag_coefficient", &hlv::drive::DrivetrainConfig::drag_coefficient)
        .def_readwrite("frontal_area_m2", &hlv::drive::DrivetrainConfig::frontal_area_m2)
        .def_readwrite("rolling_resistance", &hlv::drive::DrivetrainConfig::rolling_resistance)
        .def_readwrite("enable_traction_control", &hlv::drive::DrivetrainConfig::enable_traction_control)
        .def_readwrite("max_wheel_slip_ratio", &hlv::drive::DrivetrainConfig::max_wheel_slip_ratio)
        .def_readwrite("traction_control_gain", &hlv::drive::DrivetrainConfig::traction_control_gain);

    py::class_<hlv::drive::BatteryConstraints>(m, "BatteryConstraints")
        .def(py::init<>())
        .def_readwrite("max_discharge_power_kw", &hlv::drive::BatteryConstraints::max_discharge_power_kw)
        .def_readwrite("max_charge_power_kw", &hlv::drive::BatteryConstraints::max_charge_power_kw)
        .def_readwrite("continuous_power_kw", &hlv::drive::BatteryConstraints::continuous_power_kw)
        .def_readwrite("temp_optimal_c", &hlv::drive::BatteryConstraints::temp_optimal_c)
        .def_readwrite("temp_soft_limit_c", &hlv::drive::BatteryConstraints::temp_soft_limit_c)
        .def_readwrite("temp_hard_limit_c", &hlv::drive::BatteryConstraints::temp_hard_limit_c)
        .def_readwrite("temp_cold_limit_c", &hlv::drive::BatteryConstraints::temp_cold_limit_c)
        .def_readwrite("soc_min_normal", &hlv::drive::BatteryConstraints::soc_min_normal)
        .def_readwrite("soc_min_critical", &hlv::drive::BatteryConstraints::soc_min_critical)
        .def_readwrite("soc_max_regen", &hlv::drive::BatteryConstraints::soc_max_regen)
        .def_readwrite("soc_max_full", &hlv::drive::BatteryConstraints::soc_max_full)
        .def_readwrite("voltage_min", &hlv::drive::BatteryConstraints::voltage_min)
        .def_readwrite("voltage_nominal", &hlv::drive::BatteryConstraints::voltage_nominal)
        .def_readwrite("voltage_max", &hlv::drive::BatteryConstraints::voltage_max)
        .def_readwrite("max_discharge_current_a", &hlv::drive::BatteryConstraints::max_discharge_current_a)
        .def_readwrite("max_charge_current_a", &hlv::drive::BatteryConstraints::max_charge_current_a)
        .def_readwrite("continuous_current_a", &hlv::drive::BatteryConstraints::continuous_current_a);

    py::class_<hlv::drive::HLVTorqueWeights>(m, "HLVTorqueWeights")
        .def(py::init<>())
        .def_readwrite("health_influence", &hlv::drive::HLVTorqueWeights::health_influence)
        .def_readwrite("degradation_influence", &hlv::drive::HLVTorqueWeights::degradation_influence)
        .def_readwrite("entropy_influence", &hlv::drive::HLVTorqueWeights::entropy_influence)
        .def_readwrite("metric_stress_influence", &hlv::drive::HLVTorqueWeights::metric_stress_influence)
        .def_readwrite("eco_power_fraction", &hlv::drive::HLVTorqueWeights::eco_power_fraction)
        .def_readwrite("normal_power_fraction", &hlv::drive::HLVTorqueWeights::normal_power_fraction)
        .def_readwrite("sport_power_fraction", &hlv::drive::HLVTorqueWeights::sport_power_fraction)
        .def_readwrite("min_torque_fraction", &hlv::drive::HLVTorqueWeights::min_torque_fraction)
        .def_readwrite("max_hlv_derate", &hlv::drive::HLVTorqueWeights::max_hlv_derate)
        .def_readwrite("critical_health_threshold", &hlv::drive::HLVTorqueWeights::critical_health_threshold)
        .def_readwrite("enable_predictive_limiting", &hlv::drive::HLVTorqueWeights::enable_predictive_limiting)
        .def_readwrite("forecast_horizon_cycles", &hlv::drive::HLVTorqueWeights::forecast_horizon_cycles)
        .def_readwrite("forecast_safety_margin", &hlv::drive::HLVTorqueWeights::forecast_safety_margin)
        .def_readwrite("enable_cell_aware_limiting", &hlv::drive::HLVTorqueWeights::enable_cell_aware_limiting);

    py::class_<hlv::drive::TorqueConfig>(m, "TorqueConfig")
        .def(py::init<>())
        .def_readwrite("drivetrain", &hlv::drive::TorqueConfig::drivetrain)
        .def_readwrite("battery", &hlv::drive::TorqueConfig::battery)
        .def_readwrite("hlv_weights", &hlv::drive::TorqueConfig::hlv_weights)
        .def_readwrite("drive_mode", &hlv::drive::TorqueConfig::drive_mode)
        .def_readwrite("regen_mode", &hlv::drive::TorqueConfig::regen_mode)
        .def_readwrite("enable_launch_control", &hlv::drive::TorqueConfig::enable_launch_control)
        .def_readwrite("enable_overboost", &hlv::drive::TorqueConfig::enable_overboost)
        .def_readwrite("overboost_duration_s", &hlv::drive::TorqueConfig::overboost_duration_s)
        .def_readwrite("overboost_power_multiplier", &hlv::drive::TorqueConfig::overboost_power_multiplier)
        .def_readwrite("enable_thermal_prediction", &hlv::drive::TorqueConfig::enable_thermal_prediction)
        .def_readwrite("enable_cell_aware_limiting", &hlv::drive::TorqueConfig::enable_cell_aware_limiting)
        .def_readwrite("enable_smooth_transitions", &hlv::drive::TorqueConfig::enable_smooth_transitions)
        .def_readwrite("transition_time_constant_s", &hlv::drive::TorqueConfig::transition_time_constant_s)
        .def_readwrite("enable_logging", &hlv::drive::TorqueConfig::enable_logging)
        .def_readwrite("logging_interval_s", &hlv::drive::TorqueConfig::logging_interval_s);

    py::class_<hlv::drive::TorqueResult>(m, "TorqueResult")
        .def(py::init<>())
        .def_readwrite("max_drive_torque_nm", &hlv::drive::TorqueResult::max_drive_torque_nm)
        .def_readwrite("max_regen_torque_nm", &hlv::drive::TorqueResult::max_regen_torque_nm)
        .def_readwrite("front_torque_fraction", &hlv::drive::TorqueResult::front_torque_fraction)
        .def_readwrite("rear_torque_fraction", &hlv::drive::TorqueResult::rear_torque_fraction)
        .def_readwrite("max_power_kw", &hlv::drive::TorqueResult::max_power_kw)
        .def_readwrite("estimated_efficiency", &hlv::drive::TorqueResult::estimated_efficiency)
        .def_readwrite("base_motor_scaling", &hlv::drive::TorqueResult::base_motor_scaling)
        .def_readwrite("hlv_scaling", &hlv::drive::TorqueResult::hlv_scaling)
        .def_readwrite("thermal_scaling", &hlv::drive::TorqueResult::thermal_scaling)
        .def_readwrite("soc_scaling", &hlv::drive::TorqueResult::soc_scaling)
        .def_readwrite("health_scaling", &hlv::drive::TorqueResult::health_scaling)
        .def_readwrite("cell_balancing_scaling", &hlv::drive::TorqueResult::cell_balancing_scaling)
        .def_readwrite("overall_scaling", &hlv::drive::TorqueResult::overall_scaling)
        .def_readwrite("health_derate_active", &hlv::drive::TorqueResult::health_derate_active)
        .def_readwrite("thermal_derate_active", &hlv::drive::TorqueResult::thermal_derate_active)
        .def_readwrite("entropy_derate_active", &hlv::drive::TorqueResult::entropy_derate_active)
        .def_readwrite("metric_derate_active", &hlv::drive::TorqueResult::metric_derate_active)
        .def_readwrite("soc_derate_active", &hlv::drive::TorqueResult::soc_derate_active)
        .def_readwrite("weak_cell_derate_active", &hlv::drive::TorqueResult::weak_cell_derate_active)
        .def_readwrite("power_limit_active", &hlv::drive::TorqueResult::power_limit_active)
        .def_readwrite("traction_limit_active", &hlv::drive::TorqueResult::traction_limit_active)
        .def_readwrite("overboost_active", &hlv::drive::TorqueResult::overboost_active)
        .def_readwrite("launch_control_active", &hlv::drive::TorqueResult::launch_control_active)
        .def_readwrite("limp_mode_active", &hlv::drive::TorqueResult::limp_mode_active)
        .def_readwrite("computation_time_us", &hlv::drive::TorqueResult::computation_time_us)
        .def_readwrite("limiting_factor", &hlv::drive::TorqueResult::limiting_factor)
        .def_readwrite("confidence_level", &hlv::drive::TorqueResult::confidence_level);

    py::class_<hlv::drive::TorqueDiagnostics>(m, "TorqueDiagnostics")
        .def(py::init<>())
        .def_readwrite("average_torque_nm", &hlv::drive::TorqueDiagnostics::average_torque_nm)
        .def_readwrite("peak_torque_nm", &hlv::drive::TorqueDiagnostics::peak_torque_nm)
        .def_readwrite("average_power_kw", &hlv::drive::TorqueDiagnostics::average_power_kw)
        .def_readwrite("peak_power_kw", &hlv::drive::TorqueDiagnostics::peak_power_kw)
        .def_readwrite("total_energy_kwh", &hlv::drive::TorqueDiagnostics::total_energy_kwh)
        .def_readwrite("regen_energy_kwh", &hlv::drive::TorqueDiagnostics::regen_energy_kwh)
        .def_readwrite("average_efficiency", &hlv::drive::TorqueDiagnostics::average_efficiency)
        .def_readwrite("motor_efficiency", &hlv::drive::TorqueDiagnostics::motor_efficiency)
        .def_readwrite("inverter_efficiency", &hlv::drive::TorqueDiagnostics::inverter_efficiency)
        .def_readwrite("max_motor_temp_c", &hlv::drive::TorqueDiagnostics::max_motor_temp_c)
        .def_readwrite("max_inverter_temp_c", &hlv::drive::TorqueDiagnostics::max_inverter_temp_c)
        .def_readwrite("max_battery_temp_c", &hlv::drive::TorqueDiagnostics::max_battery_temp_c)
        .def_readwrite("average_hlv_scaling", &hlv::drive::TorqueDiagnostics::average_hlv_scaling)
        .def_readwrite("derate_event_count", &hlv::drive::TorqueDiagnostics::derate_event_count)
        .def_readwrite("total_derate_time_s", &hlv::drive::TorqueDiagnostics::total_derate_time_s)
        .def_readwrite("update_count", &hlv::drive::TorqueDiagnostics::update_count)
        .def_readwrite("total_time_s", &hlv::drive::TorqueDiagnostics::total_time_s)
        .def("reset", &hlv::drive::TorqueDiagnostics::reset);

    py::class_<hlv::drive::HLVTorqueManager>(m, "HLVTorqueManager")
        .def(py::init<>())
        .def(py::init<const hlv::drive::TorqueConfig&>(), py::arg("config"))
        .def("init", &hlv::drive::HLVTorqueManager::init, py::arg("config"))
        .def("set_drive_mode", &hlv::drive::HLVTorqueManager::set_drive_mode, py::arg("mode"))
        .def("set_regen_mode", &hlv::drive::HLVTorqueManager::set_regen_mode, py::arg("mode"))
        .def("get_config", &hlv::drive::HLVTorqueManager::get_config)
        .def("compute_torque_limit", &hlv::drive::HLVTorqueManager::compute_torque_limit,
             py::arg("enhanced"), py::arg("motor_speed_rpm"), py::arg("dt") = 0.01, py::arg("pack_diagnostics") = nullptr)
        .def("get_diagnostics", &hlv::drive::HLVTorqueManager::get_diagnostics)
        .def("reset_diagnostics", &hlv::drive::HLVTorqueManager::reset_diagnostics)
        .def("get_motor_temperature", &hlv::drive::HLVTorqueManager::get_motor_temperature)
        .def("get_inverter_temperature", &hlv::drive::HLVTorqueManager::get_inverter_temperature)
        .def("get_status_summary", &hlv::drive::HLVTorqueManager::get_status_summary)
        .def_static("get_version", &hlv::drive::HLVTorqueManager::get_version);
}
